if [ -z $1 ]
then
	echo "Please specify the file you want to compile(with no suffix)"
	exit
fi

echo "Compiling $1"
latex $1.tex
dvips $1.dvi
ps2pdf $1.ps

echo
echo "Deleting temp file generated by $1"
rm *.log *.aux
rm *.dvi *.ps

echo
echo "Done compiling $1"