if [ -z $1 ]
then
	echo "Please specify the file you want to compile(with no suffix)"
	exit
fi

cd src

echo "Compiling $1"
latex $1.tex
dvipdfm $1.dvi


# Move compiled file out
mkdir ../../cv-pdf -p
mv $1.pdf ../../cv-pdf/

echo
echo "Deleting temp file generated by $1"
rm *.log *.aux *.dvi

cd ..

echo
echo "Done compiling $1"